# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.3.0"

default_platform :ios

platform :ios do
  before_all do
    puts "🌯 🌯 🌯 Doin' some fastlane 🌯 🌯 🌯"
  end

  desc "Build IPA with janky macOS Sierra Keychain"
  lane :build_app_with_janky_keychain do
    gym(scheme: "FastlaneApp",
        configuration: "Debug",
        silent: true,
        clean: true,
        include_symbols: true,
        include_bitcode: true)
  end

  after_all do |lane|
    puts "🌮 🌮 🌮  Taco Time! 🌮 🌮 🌮"
  end

  error do |lane, exception|
    puts "Uh oh..."
  end
end

# Things to investigate
# 1. Using match to handle the certs and provisioning profiles


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
