# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.3.0"

default_platform :ios

platform :ios do
  before_all do
    puts "🌯 🌯 🌯 Doin' some fastlane 🌯 🌯 🌯"
  end

  desc "Build IPA with janky macOS Sierra Keychain"
  lane :build_app_with_janky_keychain do
    # Be sure that your provisioning profiles are loaded in the app...

    # Now we do the dirty work of handling this crappy macOS Sierra bug
    # https://openradar.appspot.com/28524119
    # http://stackoverflow.com/questions/39868578/security-codesign-in-sierra-keychain-ignores-access-control-settings-and-ui-p

    # First, let's see if we have the jank keychain already, if we do, then
    # we delete it

    has_jank_keychain = File.exist? (File.expand_path "~/Library/Keychains/billy_goat_is_janky.keychain-db")
    delete_keychain(name: "billy_goat_is_janky.keychain") if has_jank_keychain

    # Now let's create the jank keychain

    create_keychain(name: "billy_goat_is_janky.keychain",
                    timeout: "false",
                    unlock: "true",
                    password: "<change-this-to-whatever-you-want>")

    # Ok, we have a temp keychain now, let's add all our certs

    dev-cert_path = File.expand_path "~/wherever-your-certs-are/a-cert-dev.p12"
    dis-cert_path = File.expand_path "~/wherever-your-certs-are/a-cert-dis.p12"

    import_certificate(keychain_name: "billy_goat_is_janky.keychain",
                       keychain_password: "<whatever-it-is-you-made-it>"
                       certificate_path: dev-cert_path,
                       certificate_password: "<also-change-this-to-whatever-you-want>")

    import_certificate(keychain_name: "billy_goat_is_janky.keychain",
                       keychain_password: "<whatever-it-is-you-made-it>"
                       certificate_path: dis-cert_path,
                       certificate_password: "<also-change-this-to-whatever-you-want>")
                       
    # Since we have a janky keychain, let's unlock it and make it the default keychain

    unlock_keychain(path: "billy_goat_is_janky.keychain",
                    password: "<Again-enter-it-here>",
                    set_default: "true")

    # Now we are ready to do a build...

    gym(scheme: "FastlaneApp",
        silent: true,
        clean: true,
        include_symbols: true,
        include_bitcode: true)

    # We are done, so let's set the login keychain back as the default, we can do this
    # with the unlock_keychain action

    unlock_keychain(path: "login",
                    password: "<login-keychain-password>",
                    set_default: "true")

    # Finally, we delete the janky keychain

    delete_keychain(name: "billy_goat_is_janky.keychain")

    # =(
  end

  after_all do |lane|
    puts "🌮 🌮 🌮  Taco Time! 🌮 🌮 🌮"
  end

  error do |lane, exception|
    puts "Uh oh..."
  end
end

# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
